version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: transactions
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
